export const FETCH_DAOS_SUCCESS = "FETCH_DAOS_SUCCESS";
export const FETCH_PUBLIC_DAOS_SUCCESS = "FETCH_DAOS_SUCCESS";
export const FETCH_DAOS_PENDING = "FETCH_DAOS_PENDING";
export const FETCH_DAOS_ERROR = "FETCH_DAOS_ERROR";
export const FETCH_DAOS_COUNT = 'FETCH_DAOS_COUNT';

export const FETCH_NOTE_SUCCESS = 'FETCH_NOTE_SUCCESS';
export const FETCH_DESCRIPTION_SUCCESS = 'FETCH_DESCRIPTION_SUCCESS';
export const CLEAR_DAO_NOTE = 'CLEAR_DAO_NOTE';
export const CLEAR_ADDRESS_INVITED_MEMBER = 'CLEAR_ADDRESS_INVITED_MEMBER';

export const ADD_NEW_DAO = 'ADD_NEW_DAO';

export const FETCH_ACCOUNT = 'FETCH_ACCOUNT';

export const FETCH_CHAIN_ID = 'FETCH_CHAIN_ID';
export const FETCH_CONTRACT = 'FETCH_CONTRACT';