export const FETCH_CITIZENS_SUCCESS = "ETCH_CITIZENS_SUCCESS";
export const FETCH_DAOS_SUCCESS = "ETCH_DAOS_SUCCESS";
export const FETCH_PUBLIC_DAOS_SUCCESS = "ETCH_DAOS_SUCCESS";
export const FETCH_CITIZENS_PENDING = "FETCH_CITIZENS_PENDING";
export const FETCH_DAOS_PENDING = "FETCH_DAOS_PENDING";
export const FETCH_CITIZENS_ERROR = "FETCH_CITIZENS_ERROR";
export const FETCH_DAOS_ERROR = "FETCH_DAOS_ERROR";
export const FETCH_CITIZENS_COUNT = 'FETCH_CITIZENS_COUNT';
export const FETCH_DAOS_COUNT = 'FETCH_DAOS_COUNT';

export const FETCH_NOTE_SUCCESS = 'FETCH_NOTE_SUCCESS';
export const FETCH_DESCRIPTION_SUCCESS = 'FETCH_DESCRIPTION_SUCCESS';
export const CLEAR_CITIZEN_NOTE = 'CLEAR_CITIZEN_NOTE';
export const CLEAR_DAO_NOTE = 'CLEAR_DAO_NOTE';

export const ADD_NEW_CITIZEN = 'ADD_NEW_CITIZEN';
export const ADD_NEW_DAO = 'ADD_NEW_DAO';

export const FETCH_ACCOUNT = 'FETCH_ACCOUNT';

export const FETCH_CHAIN_ID = 'FETCH_CHAIN_ID';
export const FETCH_CONTRACT = 'FETCH_CONTRACT';